title: Lijin Chen's Homepage
page-top-title: Lijin Chen
top-section-bg-text: Be what you wanna be
home-subtitle: Lijin Chen&ensp;|&ensp;陈俐锦
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
